import turtle
turtle.penup()
turtle.seth(-135)
turtle.fd(200)
turtle.pendown() 
turtle.seth(0)
turtle.penup()
turtle.fd(100)
turtle.pendown()
turtle.fd(200)
turtle.penup()
turtle.fd(100)
turtle.seth(90)
turtle.penup()
turtle.fd(100)
turtle.pendown()
turtle.fd(200)
turtle.penup()
turtle.fd(100)
turtle.seth(180)
turtle.penup()
turtle.fd(100)
turtle.pendown()
turtle.fd(200)
turtle.penup()
turtle.fd(100)
turtle.seth(-90)
turtle.penup()
turtle.fd(100)
turtle.pendown()
turtle.fd(200)
turtle.penup()
turtle.fd(100)


